# syntax=docker/dockerfile:1

FROM python:3.9.7-alpine
WORKDIR /backend
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY source .

CMD ["flask", "--app", "server", "--debug", "run", "--host=0.0.0.0"]
